Next
netcontrold/netcontrold-py pull request #48
Opened 2020-03-09 13:33 UTC by Shrutikabansal

2020-03-09 15:42 UTC, gmuthukr commented
Please mention what this PR would do in subject (and in description if needed).

2020-03-09 15:52 UTC, gmuthukr requested changes
Rework on how pmd objects are created and resubmit with actual tests.

2020-03-09 15:52 UTC, gmuthukr commented on netcontrold/tests/lib/test_pmd_load_variance.py
> +_BASIC_CPU_INFO = """
This is not cpu info!.

2020-03-09 15:52 UTC, gmuthukr commented on netcontrold/tests/lib/test_pmd_load_variance.py
> +        self.pmd_map = dataif.get_pmd_stats({})
No ack for this approach!...
All you need to do is start creating pmd objects manually as in PR #47 and then call pmd_load_variance.
When you set various cycle data, check how pmd_load is calculated in the application and compare manually calculated value with what returned. Of course, add negative tests as well as proposed in the doc.

Thanks.

2020-03-10 18:32 UTC, Shrutikabansal commented
Here i changed in one test case for pmd_load_variance.

2020-03-11 07:00 UTC, Shrutikabansal commented
Changes done in dataif.py file and test file

2020-03-11 10:58 UTC, gmuthukr requested changes

2020-03-11 10:58 UTC, gmuthukr commented on netcontrold/lib/dataif.py
> +    update_pmd_load(pmd_map)
The caller has to ensure updating pmd load before calling this function. Discard this change.

2020-03-11 10:58 UTC, gmuthukr commented on netcontrold/tests/lib/test_pmd_load_variance.py
> -_BASIC_DATA = """
Please squash your commits you work for these test and submit one for test ..

2020-03-11 10:58 UTC, gmuthukr commented on netcontrold/tests/lib/test_pmd_load_variance.py
> +class TestRebalDryrunRR_OnePmd(TestCase):
I think something you screwed up pulling old commit that I made .. it shows my additions.... I drop reviewing it and wait for new PR with fresh code changes.
Thanks.

2020-03-12 05:42 UTC, closed without merging